version: '3'
# https://blog.adamzolo.com/dockerizing-mariadb-with-a-custom-sql-script-in-development/

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: flowerfulfort/roadscroll-db:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=roadimage
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=roadimage
    volumes:
      - F:\roadscroll\mariadb:/var/lib/mysql
      # - scroll_db:/var/lib/mysql
    ports:
      - 29988:3306
    # Debug용 포트. 29988로 접속하여 디버그.
    restart: 'unless-stopped'

  nginx:
    container_name: nginx-road
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: flowerfulfort/roadscroll-server:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - C:\Users\cquser\docker\letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb
      - node
      - backend-api
    restart: 'unless-stopped'

  backend-api:
    container_name: backend-api
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    image: flowerfulfort/roadscroll-api:latest
    volumes:
      - F:\roadscroll\images:/opt/images
      - F:\roadscroll\geojsons:/opt/geojsons
      - F:\roadscroll\masks:/opt/masks
      - F:\roadscroll\tiles:/opt/tiles
      # - scroll_data:/opt
    depends_on:
      - mariadb
    restart: 'unless-stopped'

  node:
    container_name: console
    build:
      context: .
      dockerfile: Dockerfile
    image: flowerfulfort/roadscroll-console:latest
    depends_on:
      - backend-api
    restart: 'unless-stopped'
